#include <iostream> // header file library or preprocessor to allow work with input and output functions
 using namespace std;
int main(){   // main is a function under curly brackets which whole code executed
    cout << "Hello World \n";  // to get output
   cout << "welcome to c++ Class \n";
    cout << "My Name is Hardik Joshi \n";
    cout<<  "I am learning C++" << endl << "Writing first code in C++" << endl; // endl is used to separate two statement in  different lines
    // Insert a new line
     cout << "Hardik" << endl << "joshi";
    return 0; // return 0 ends the main() statement ctrl / also used to comment the line
}
